### ISSUE TITLE
Workflow of User Checkin

### ISSUE THREAD

**Issue by BaReinhard** [ChrisHammond/ClubReadyCalls#1]
Hey Chris,
I am still waiting on getting an API Key from support, but I thought I would do my due diligence and get some information if possible.

So I am working on a Desktop Application using C# for Win Forms to personalize User Check-In a bit more for our members.

I am curious as to what the best workflow would be for checkin in a member?

i.e. grab member barcode from user, get /user/find, return user id, post /user/checkin?

or could something more to the point be done?

**Comment by ChrisHammond** [comment]
Thanks for the note, glad to see someone stumbled across this code, I'll get some more examples going soon! For now, you workflow could be very simple. You will need the barcode, so either you retrieve it via the API via with the GET call to /user/find or you could retrieve it from the user in some form.

After retrieving the API key you can perform the POST to /user/checkin that is simply going to return a TRUE or FALSE response.

If it returns falls, you might want to make an API call GET /users/{userid} in which you can retrieve the "FULL DETAILS" to see if a user either has an Alert (HasAlert), is past due "HasPastDue", or they are Frozen.

**Comment by BaReinhard** [comment]
I'm glad there is this resource so thank you for the documentation. My goal will ultimately be to create a win form app similar to the check in kiosk, that either takes their phone number or barcode and allows for access to the club.

I went this route, because we are using a turnstile in our facility and requires com port access. Additionally, we are using the class checkin app so having the option for members to use their phone number for both (given you can find users based on phone number alone) which will help with not needing to memorize two numbers invade they forget their barcode at home.

Once I get access to an API key I'll be able to play around more with what may or may not be possible.

Also thanks for the idea to query full details in case I get a false response.

If I get things working, I don't mind sending over some of the code so you won't have to come up with all the examples on your own.

Another nice thing to have in the docs would be a description of where we can find the storeid on clubready as I haven't been able to come across that.

**Comment by ChrisHammond** [comment]
If you're only a single location, they should provide it to you with the API key. You can also find it if you're logged into ClubReady with a staff account, up in the top right corner click on the downward triangle next to your name/photo. The First number there after "ID" is the StoreID followed by that staff person's UserID.

If you've got multiple locations and a "chain" in ClubReady, the API endpoints allow you to retrieve a list of stores for a particular chain.

**Comment by ChrisHammond** [comment]
Had a few more thoughts on this early this morning. If you guys aren't using Keytags for barcodes today, you might simply start assigning Member's phone number as their barcode, that's one option, could help cut down on API calls not having to lookup an individual by Phone number first.

If you do a /users/find call with a phone number and it returns multiple users, you'll need to have some way to figure out which is the correct user (might be user input/selection that decides)

**Comment by BaReinhard** [comment]
Thanks for the information on the storeID.

Unfortunately, we have been issuing barcodes (as its simply easier for members). That being said I may look into checking with just the barcode first, then if it returns false, check a local file (however I choose to implement this) to look for the user based on phone number, get the user ID then try checkin again with userID from phone number. Then if this returns false will alert the member to pay for their membership. This will work for our implementation as the only time they won't be able to login is because they owe for an item or a membership. It's a bit janky but overall I think it would work better than constantly banging on the api.

If you guys do have a limit on the API calls, what is that limit?

**Comment by ChrisHammond** [comment]
No limit at this time, but we may implement one soon, so don't abuse :D

**Comment by BaReinhard** [comment]
Ha good to know, at most we have 250 members come in a day. If we assume half the members input the code incorrectly, that would be 750 API calls/day. Then assuming a few members forget their barcode should roughly only be 800-850/day. This is probably an over assumption on my part, but I'm guessing when you do limit API calls, it would be calls/hour than calls/day. Which I feel this implementation would be fine for. If it does reach the call limit I'll just simply rethink how to implement this.


Thank you for all the help and support.

Aside from creating issues for any pressing questions is there a better place to submit them than here?

**Comment by ChrisHammond** [comment]
We would likely limit within a timeframe, minutes or hours, so unless you're hitting us with hundreds of calls a minute, you'll likely be fine.

**Comment by BaReinhard** [comment]
Thank you for all the help and support.

Aside from creating issues for any pressing questions is there a better place to submit them than here?

**Comment by ChrisHammond** [comment]
Right now we don't have a great mechanism for this type of communication, so here, or emailing me directly chammond - clubready.com

**Comment by BaReinhard** [comment]
Alright, so I finally got the API key, and have got the code running, unfortunately, it seems as though I get a 401, "Unauthorized for Store"

```
Object {data: "", status: 401, config: Object, statusText: "Unauthorized for Store", headers: function}
```
But if I use your Api page to use the same params it returns true. The same goes for the google chrome postman addon

Is there something I am doing incorrectly with the post request?

**Comment by ChrisHammond** [comment]
You can use HTTP or HTTPS for the API calls

**Comment by BaReinhard** [comment]
I've been going through the API docs and testing each of the `/users` ones and can't seem to find a call that will return the users picture. Am I missing something or is this a resource that is not allowed from the API.

Additionally, I was wondering if you might provide a dummy account/API key to test the API's on. Especially, for testing user checkin it begins to muck up our attendance reports. 

I know that in similar courses to the one I am taking that teach web development, that this type of project would be extremely beneficial for students, but could also lead to some more open-source documentation/resources for other club owners in which they could implement who might not have as much development background.

**Comment by ChrisHammond** [comment]
Please shoot me an email ;) chammond - clubready.com
